<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  <a href="/timeline"><img src="/img/urso.png" class="menuIco" /></a>
	  </div>
	</div>
</nav>

<div class="container-fluid mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

		<div class="perfil">
				<div class="perfilTopo">
				<div class="navbar-nav">
						<a class="my-2 mt-5" href="/timeline">
							<span class="menuLink"><i class="fas fa-igloo pr-2"></i> Home</span>
						</a>

						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="fas fa-hashtag pr-2"></i> Explore</span>
						</a>
						
						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="far fa-bell pr-2"></i> Notificações</span>
						</a>
						
						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="far fa-envelope pr-2"></i> Mensagens</span>
						</a>

						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="far fa-bookmark pr-2"></i> Favoritos</span>
						</a>

						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="far fa-list-alt pr-2"></i> Listas</span>
						</a>

						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="fas fa-user-alt pr-2"></i> Perfil</span>
						</a>

						<a class="my-2" href="/timeline">
							<span class="menuLink"><i class="fas fa-caret-down pr-2"></i> Mais</span>
						</a>

						<a class="my-2" href="/sair">
							<span class="menuLink"><i class="fas fa-sign-out-alt pr-2"></i> Sair</span>
						</a>
					</div>
				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome text-capitalize">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets['total_tweet'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores['total_seguidores'] ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="bloco">
						<div class=" card-color">
							<form method="get" action="/quem_seguir">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="input-pesquisa" placeholder="Pesquisar no Twitter">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="bloco">
							<div class="card-color">
								<div class="row">
									<div class="col-md-6 text-capitalize">
										<?= $usuario['nome'] ?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<?php if($usuario['seguindo_sn'] == 0) { ?>
												<a href="/acao?acao=seguir&id_usuario=<?=$usuario['id']?>" class="btn btn-seguir">Seguir</a>
											<?php } ?>

											<?php if($usuario['seguindo_sn'] == 1) { ?>
												<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>" onmouseover="mudaDescricao(this)" onmouseout="voltaDescricao(this)" class="btn btn-deixar">Seguindo</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>